name: Collect Code Statistics

on:
  schedule:
    - cron: "03 01 * * *"

jobs:
  collect-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Collect Code Statistics
        run: node collect-code.js
        env:
          GITHUB_TOKEN: ${{ secrets.COUNTER_TOKEN }}
