name: Update Readme

on:
  schedule:
    - cron: "0 */24 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Count Code for Backend
        run: |
          total_lines=$(curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/MainProjectsB/WE-ARE-THE-PARTY-BACKEND/contents?recursive=1" | jq -r '.[] | select(.type == "file" and (.name | endswith(".js", ".ts", ".jsx", ".css"))) | .size' | awk '{ total += $1 } END { print total }')
          sed -i "s/Toplam Kod Satır Sayısı Proje A: .*/Toplam Kod Satır Sayısı Proje A: $total_lines/" README.md

      - name: Count Code for Frontend
        run: |
          total_lines=$(curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/MainProjectsB/WE-ARE-THE-PARTY-FRONT/contents?recursive=1" | jq -r '.[] | select(.type == "file" and (.name | endswith(".js", ".ts", ".jsx", ".css"))) | .size' | awk '{ total += $1 } END { print total }')
          sed -i "s/Toplam Kod Satır Sayısı Proje B: .*/Toplam Kod Satır Sayısı Proje B: $total_lines/" README.md

      # Diğer projeler için de benzer şekilde adımlar ekleyebilirsiniz

      - name: Update README
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -am "Güncellenmiş kod sayıları"
          git push
